# Generated by Django 5.1.5 on 2025-02-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_date', models.CharField(max_length=30)),
                ('req_desc', models.CharField(max_length=30)),
            ],
        ),
    ]
