# Generated by Django 5.1.5 on 2025-02-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='amount',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_request',
            name='req_date',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_request',
            name='req_status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
