# Generated by Django 5.1.5 on 2025-02-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_tbl_request_amount_tbl_request_req_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
