# Generated by Django 5.1.5 on 2025-02-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_delete_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_date', models.DateField(auto_now_add=True)),
                ('req_desc', models.CharField(max_length=30)),
                ('req_status', models.CharField(max_length=30)),
                ('req_date', models.DateField()),
                ('amount', models.CharField(max_length=30)),
            ],
        ),
    ]
