# Generated by Django 5.1.5 on 2025-02-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_tbl_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
