# Generated by Django 5.1.5 on 2025-02-25 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_tbl_technician_place'),
        ('User', '0008_delete_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_date', models.DateField()),
                ('req_desc', models.CharField(max_length=30)),
                ('req_status', models.CharField(max_length=30)),
                ('req_date', models.DateField(auto_now_add=True)),
                ('amount', models.CharField(max_length=30)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_technician')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
