# Generated by Django 5.1.5 on 2025-02-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_tbl_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_request',
            name='req_status',
            field=models.IntegerField(default=0),
        ),
    ]
