# Generated by Django 5.1.5 on 2025-03-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_tbl_request_req_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_request',
            old_name='amount',
            new_name='req_amount',
        ),
    ]
