# Generated by Django 5.1.5 on 2025-03-03 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_tbl_technician_place'),
        ('User', '0012_tbl_booking_tbl_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='deliveryboy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_deliveryboy'),
        ),
    ]
