# Generated by Django 5.1.5 on 2025-03-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alter_tbl_booking_deliveryboy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cart',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='product',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
