# Generated by Django 5.1.5 on 2025-03-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_tbl_booking_tbl_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cart',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='product',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
