# Generated by Django 5.1.5 on 2025-03-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_tbl_technician_place'),
        ('User', '0017_tbl_booking_tbl_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('assign_status', models.IntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('deliveryboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_deliveryboy')),
            ],
        ),
    ]
