# Generated by Django 5.1.5 on 2025-03-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_tbl_assign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assign',
        ),
    ]
