# Generated by Django 5.1.5 on 2025-04-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_tbl_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='workdone_date',
            field=models.DateField(null=True),
        ),
    ]
