# Generated by Django 5.1.5 on 2025-04-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_tbl_request_workdone_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='delivered_date',
            field=models.DateField(null=True),
        ),
    ]
