# Generated by Django 5.1.5 on 2025-04-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_tbl_booking_delivered_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
