# Generated by Django 5.2 on 2025-04-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
