# Generated by Django 5.1.5 on 2025-02-19 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0008_delete_tbl_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_addproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_details', models.CharField(max_length=30)),
                ('product_photo', models.FileField(upload_to='Assets/File/Shop/product photo')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subcategory')),
            ],
        ),
    ]
