# Generated by Django 5.1.5 on 2025-02-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_tbl_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_stock',
            new_name='tbl_addstock',
        ),
    ]
