# Generated by Django 5.1.5 on 2025-02-20 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_delete_tbl_reply'),
        ('Shop', '0003_rename_tbl_stock_tbl_addstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_addstock',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subcategory'),
        ),
    ]
