# Generated by Django 5.1.5 on 2025-02-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_alter_tbl_addstock_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_addstock',
        ),
    ]
