# Generated by Django 5.1.5 on 2025-02-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_tbl_addstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_addstock',
            name='stock_date',
        ),
    ]
