# Generated by Django 5.1.5 on 2025-02-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_remove_tbl_addstock_stock_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_addstock',
        ),
    ]
