# Generated by Django 5.1.5 on 2025-02-20 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_delete_tbl_addstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_addstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_addproducts')),
            ],
        ),
    ]
