# Generated by Django 5.1.5 on 2025-02-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_tbl_addstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_addproducts',
            name='product_price',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
