# Generated by Django 5.1.5 on 2025-03-03 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_tbl_technician_place'),
        ('Shop', '0010_tbl_addproducts_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_addproducts',
            name='shop',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop'),
            preserve_default=False,
        ),
    ]
