# Generated by Django 5.1.5 on 2025-03-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_tbl_addproducts_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_addproducts',
            name='shop',
        ),
    ]
