# Generated by Django 5.1.5 on 2025-03-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_remove_tbl_addproducts_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_addstock',
            name='product',
        ),
        migrations.DeleteModel(
            name='tbl_addproducts',
        ),
        migrations.DeleteModel(
            name='tbl_addstock',
        ),
    ]
