# Generated by Django 5.1.5 on 2025-03-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0008_delete_tbl_reply'),
        ('Guest', '0012_tbl_technician_place'),
        ('Shop', '0013_remove_tbl_addstock_product_delete_tbl_addproducts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_addproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_details', models.CharField(max_length=30)),
                ('product_photo', models.FileField(upload_to='Assets/File/Shop/product photo')),
                ('product_price', models.CharField(max_length=30)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_addstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_addproducts')),
            ],
        ),
    ]
