# Generated by Django 5.1.5 on 2025-03-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_addstock',
        ),
    ]
