# Generated by Django 5.1.5 on 2025-03-05 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_tbl_technician_place'),
        ('Shop', '0016_tbl_addstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('deliveryboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_deliveryboy')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop')),
            ],
        ),
    ]
