# Generated by Django 5.1.5 on 2025-03-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_tbl_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_assign',
            name='assign_status',
            field=models.IntegerField(default=0),
        ),
    ]
