# Generated by Django 5.1.5 on 2025-03-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0018_tbl_assign_assign_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assign',
        ),
    ]
