# Generated by Django 5.1.5 on 2025-01-27 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_rename_place_name_tbl_subcategory_subcategory_name'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=30)),
                ('user_contact', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_district', models.CharField(max_length=30)),
                ('user_photo', models.FileField(max_length=30, upload_to='')),
                ('user_gender', models.CharField(max_length=30)),
                ('user_dob', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_signupform',
        ),
    ]
