# Generated by Django 5.1.5 on 2025-01-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_alter_tbl_user_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_district',
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.FileField(upload_to='Assets/File/User/'),
        ),
    ]
