# Generated by Django 5.1.5 on 2025-02-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='tbl_login',
        ),
    ]
