# Generated by Django 5.1.5 on 2025-02-06 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_delete_tbl_reply'),
        ('Guest', '0006_rename_login_tbl_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=30)),
                ('shop_address', models.CharField(max_length=30)),
                ('shop_contact', models.CharField(max_length=30)),
                ('shop_email', models.CharField(max_length=30)),
                ('shop_proof', models.FileField(upload_to='Assets/File/User/')),
                ('shop_license', models.FileField(upload_to='Assets/File/User/')),
                ('shop_password', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
