# Generated by Django 5.1.5 on 2025-02-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_shop',
            name='complaint_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbl_shop',
            name='shop_license',
            field=models.FileField(upload_to='Assets/File/Shop/license'),
        ),
        migrations.AlterField(
            model_name='tbl_shop',
            name='shop_proof',
            field=models.FileField(upload_to='Assets/File/Shop/proof'),
        ),
    ]
