# Generated by Django 5.1.5 on 2025-02-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_shop_complaint_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_shop',
            old_name='complaint_status',
            new_name='shop_status',
        ),
    ]
