# Generated by Django 5.1.5 on 2025-02-17 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_delete_tbl_reply'),
        ('Guest', '0009_rename_complaint_status_tbl_shop_shop_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_deliveryboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryboy_name', models.CharField(max_length=30)),
                ('deliveryboy_address', models.CharField(max_length=30)),
                ('deliveryboy_contact', models.CharField(max_length=30)),
                ('deliveryboy_email', models.CharField(max_length=30)),
                ('deliveryboy_proof', models.FileField(upload_to='Assets/File/Delivery_boy/proof')),
                ('deliveryboy_photo', models.FileField(upload_to='Assets/File/Delivery_boy/license')),
                ('deliveryboy_password', models.CharField(max_length=30)),
                ('deliveryboy_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
