# Generated by Django 5.1.5 on 2025-02-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_tbl_deliveryboy'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(max_length=30)),
                ('technician_contact', models.CharField(max_length=30)),
                ('technician_email', models.CharField(max_length=30)),
                ('technician_proof', models.FileField(upload_to='Assets/File/Technician/proof')),
                ('technician_photo', models.FileField(upload_to='Assets/File/Technician/photo')),
                ('technician_password', models.CharField(max_length=30)),
                ('technician_status', models.IntegerField(default=0)),
            ],
        ),
    ]
