# Generated by Django 5.1.5 on 2025-02-24 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_delete_tbl_reply'),
        ('Guest', '0011_tbl_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_technician',
            name='place',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place'),
            preserve_default=False,
        ),
    ]
