# Generated by Django 5.1.5 on 2025-01-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_subcategory',
            old_name='place_name',
            new_name='subcategory_name',
        ),
    ]
