# Generated by Django 5.1.5 on 2025-02-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_reply',
        ),
    ]
